/** @format */

export const GET_TICKETS_REQUEST = 'GET_TICKETS_REQUEST';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_FAIL = 'GET_TICKETS_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const NAVIGATION_SHOW_COMPONENT_SUCCESS =
	'NAVIGATION_SHOW_COMPONENT_SUCCESS';
export const NAVIGATION_SHOW_COMPONENT_REQUEST =
	'NAVIGATION_SHOW_COMPONENT_REQUEST';
export const NAVIGATION_SHOW_COMPONENT_FAIL = 'NAVIGATION_SHOW_COMPONENT_FAIL';

export const NAVIGATION_SIDEBAR_STATUS = 'NAVIGATION_SIDEBAR_STATUS';

export const PROFILE_NAV_KEY = 'PROFILE_NAV_KEY';

export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';
export const CREATE_PROJECT_RESET = 'CREATE_PROJECT_RESET';

export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';
export const GET_SINGLE_PROJECT_SUCCESS = 'GET_SINGLE_PROJECT_SUCCESS';

export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';

export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';

export const CREATE_TICKET_REQUEST = 'CREATE_TICKET_REQUEST';
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const CREATE_TICKET_FAIL = 'CREATE_TICKET_FAIL';
export const CREATE_TICKET_RESET = 'CREATE_TICKET_RESET';

export const SINGLE_TICKET_ID_REQUEST = 'SINGLE_TICKET_ID_REQUEST,';
export const SINGLE_TICKET_ID_SUCCESS = 'SINGLE_TICKET_ID_SUCCESS,';
export const SINGLE_TICKET_ID_FAIL = 'SINGLE_TICKET_ID_FAIL,';
export const SINGLE_TICKET_ID_RESET = 'SINGLE_TICKET_ID_RESET';

export const DELETE_TICKET_REQUEST = 'DELETE_TICKET_REQUEST';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_FAIL = 'DELETE_TICKET_FAIL';
export const DELETE_TICKET_RESET = 'DELETE_TICKET_RESET';

export const TICKET_COMMENT_REQUEST = 'TICKET_COMMENT_REQUEST';
export const TICKET_COMMENT_SUCCESS = 'TICKET_COMMENT_SUCCESS';
export const TICKET_COMMENT_FAIL = 'TICKET_COMMENT_FAIL';
export const TICKET_COMMENT_RESET = 'TICKET_COMMENT_RESET';

export const GET_TICKET_REQUEST = 'GET_TICKET_REQUEST';
export const GET_TICKET_SUCCESS = 'GET_TICKET_SUCCESS';
export const GET_TICKET_FAIL = 'GET_TICKET_FAIL';
export const GET_TICKET_RESET = 'GET_TICKET_RESET';

export const NEW_LOG_REQUEST = 'NEW_LOG_REQUEST';
export const NEW_LOG_SUCCESS = 'NEW_LOG_SUCCESS';
export const NEW_LOG_FAIL = 'NEW_LOG_FAIL';

export const GET_LOGS_REQUEST = 'GET_LOGS_REQUEST';
export const GET_LOGS_SUCCESS = 'GET_LOGS_SUCCESS';
export const GET_LOGS_FAIL = 'GET_LOGS_FAIL';

export const SET_MODAL_STATUS = 'SET_MODAL_STATUS';
export const SET_EDITING_TRUE = 'SET_EDITING_TRUE';
export const SET_EDITING_FALSE = 'SET_EDITING_FALSE';

export const SET_FEATURED_PROFILE_REQUEST = 'SET_FEATURED_PROFILE_REQUEST';
export const SET_FEATURED_PROFILE_SUCCESS = 'SET_FEATURED_PROFILE_SUCCESS';
export const SET_FEATURED_PROFILE_FAIL = 'SET_FEATURED_PROFILE_FAIL';
export const SET_FEATURED_PROFILE_RESET = 'SET_FEATURED_PROFILE_RESET';

export const EDIT_TICKET_REQUEST = 'EDIT_TICKET_REQUEST';
export const EDIT_TICKET_SUCCESS = 'EDIT_TICKET_SUCCESS';
export const EDIT_TICKET_FAIL = 'EDIT_TICKET_FAIL';
export const EDIT_TICKET_RESET = 'EDIT_TICKET_RESET';

export const SHOW_WIDGET_VIEW = 'SHOW_WIDGET_VIEW';

export const CREATE_ALERT = 'CREATE_ALERT';
export const DELETE_ALERT = 'DELETE_ALERT';

export const REPORT_A_BUG = 'REPORT_A_BUG';
export const REQUEST_A_FEATURE = 'REQUEST_A_FEATURE';
export const TICKET_TYPE_RESET = 'TICKET_TYPE_RESET';
export const SAVE_FORM_DATA = 'SAVE_FORM_DATA';
export const DELETE_FORM_DATA = 'DELETE_FORM_DATA';
export const SELECTED_PROJECT = 'SELECTED_PROJECT';
export const SELECTED_PROJECT_RESET = 'SELECTED_PROJECT_RESET';

export const PAGE_ONE = 'PAGE_ONE';
export const PAGE_TWO = 'PAGE_TWO';
export const PAGE_THREE = 'PAGE_THREE';

export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL';

export const GET_PRESIGNED_URL_REQUEST = 'GET_PRESIGNED_URL_REQUEST';
export const GET_PRESIGNED_URL_SUCCESS = 'GET_PRESIGNED_URL_SUCCESS';
export const GET_PRESIGNED_URL_FAIL = 'GET_PRESIGNED_URL_FAIL';

export const SEND_IMAGE_TO_S3_REQUEST = 'SEND_IMAGE_TO_S3_REQUEST';
export const SEND_IMAGE_TO_S3_SUCCESS = 'SEND_IMAGE_TO_S3_SUCCESS';
export const SEND_IMAGE_TO_S3_FAIL = 'SEND_IMAGE_TO_S3_FAIL';

export const SET_USERS_VIEW = 'SET_USERS_VIEW';
